### ISSUE TITLE
Command processing should return error instead of panic

### ISSUE THREAD

**Issue by sehz** [infinyon/flv-util#10]
Following methods in trait should not panic but return error if status is not successful
```
wait_and_check
wait
inherit
```

**Comment by nicholastmosher** [comment]
This crate is used in many of our other crates. Since the changes we want to make are going to be widely impactful, can we implement these changes by creating a new, special-purpose crate for this? Then we can incrementally migrate all of the code that uses these functions to the new crate?

**Comment by sehz** [comment]
or we can bump up major version so old code should work as is
